### ISSUE TITLE
Error at mod_rewrite block

### ISSUE THREAD

**Issue by zonky2** [Stevie-Ray/htaccess-referral-spam-blacklist-block#1]
Hi,

I have a 500 server error with yout mod_rewrite list :-(

**Comment by Stevie-Ray** [comment]
Hi xantippe, 

I run this code on multiple servers and it works for me. Could you try to remove these lines, and test if the 500 error continues to exist:

line 26: RewriteCond %{HTTP_REFERER} ^http(s)?://(._.)?darodar._$ [NC,OR]
line 85: RewriteCond %{HTTP_REFERER} ^http(s)?://(www.)?rодом.рф.*$ [NC,OR]

I validated the .htaccess file using

http://www.htaccesscheck.com/
http://www.lyxx.com/freestuff/002.html
