### ISSUE TITLE
Spam sites new

### ISSUE THREAD

**Issue by borisdifiore** [Stevie-Ray/htaccess-referral-spam-blacklist-block#109]
Stevie please add:

life.biz.ua	
infokonkurs.ru	
ruscopybook.com	
xn--d1abj0abs9d.in.ua	
saletool.ru	
flowersbazar.com	
puzzleweb.ru	
musicstock.me	
handicapvansarea.com

**Comment by Stevie-Ray** [comment]
Hi boris, thanks again i'll keep this issue open so you can add new entries in a new comment!

**Comment by borisdifiore** [comment]
Hi Stevie, you are welcome.....
I have new ones....
 
recipedays.com
woweb.com.ua
kinotorka.ru
downloadkakaotalk.com

:)

**Comment by Stevie-Ray** [comment]
i've included the new ones!
