### ISSUE TITLE
Integration with HAProxy

### ISSUE THREAD

**Issue by julianxhokaxhiu** [Stevie-Ray/htaccess-referral-spam-blacklist-block#117]
Hi,

can you please add HAProxy support? You just need to output a config file that is valid for HAProxy `acl -f` feature. See https://www.haproxy.com/doc/aloha/7.0/haproxy/acls.html#acl-f-flag

Thank you in advance,
Julian

---

Example of usage:
```
acl invalid_referer hdr_sub(referer) -i -f /etc/haproxy/banned.haproxy.conf
block if invalid_referer
```

**Comment by Stevie-Ray** [comment]
Hi Julian! Can you tell me how to write a valid HAProxy config file?

**Comment by julianxhokaxhiu** [comment]
Sorry I forgot to reply back. At the current status I didn't found an example to show, I will see if I can build up something this weekend.

**Comment by yitzhaq** [comment]
Please consider reopening this issue. The format is trivial, it's just one domain per line:

foo.com
bar.com

etc.

The only additional config required to use with HAProxy is what was already pasted in the example in the original report.

Having a file in this format available from the repo would be hugely useful, not just for HAProxy, but for anything from which someone might want to generate a custom list.

Thanks for your consideration.

**Comment by Stevie-Ray** [comment]
hi @yitzhaq please create a PR for HAProxy and i'll happily merge it.

**Comment by yitzhaq** [comment]
> hi @yitzhaq please create a PR for HAProxy and i'll happily merge it.

Done
