### ISSUE TITLE
New Spam gabysuniqueboutique.com

### ISSUE THREAD

**Issue by robwent** [Stevie-Ray/htaccess-referral-spam-blacklist-block#123]
I'm seeing a number of sites with an increase in referral traffic from the domain gabysuniqueboutique.com

**Comment by robwent** [comment]
And some more:

    auto-seo-service.com
    auto-seo-service.org
    autoseoservice.org
    autoseo-service.org

**Comment by Stevie-Ray** [comment]
Hi Robert, 

Thanks for reporting these URLs, I've added them in the latest commit e61733c.

Have a good weekend!
