### ISSUE TITLE
Join forces with matomo-org/referrer-spam-blacklist?

### ISSUE THREAD

**Issue by vdboor** [Stevie-Ray/htaccess-referral-spam-blacklist-block#126]
I noticed there is another spam blacklist: https://github.com/matomo-org/referrer-spam-blacklist/blob/master/spammers.txt Perhaps it would help (and save time) to join forces? Thanks for this list!

**Comment by Stevie-Ray** [comment]
Hi @vdboor,

First of all thanks for your feedback 👌

I'm aware of the work Piwiki / Matomo did and used one of there user contributions in [#468](https://github.com/matomo-org/referrer-spam-blacklist/issues/468) to create the IIS web.config. As you maybe have noticed the domain list that I've gathered for this repository is (at the time of writing) more than 3 times the size of the spam list Matomo uses. It also includes other sources like [digmato](https://digmato.com/google-analytics/referral-spam). If your interested in combining sources have a look at [this](https://github.com/openix/blacklist/blob/master/index.php) repo or write your own bundler.
