### ISSUE TITLE
Please add this refferer too

### ISSUE THREAD

**Issue by Mecanik** [Stevie-Ray/htaccess-referral-spam-blacklist-block#128]
First of all, I would like to thank you for the massive list that you are maintaining.

And second, if you could add this to the refferer list as well:

` referrer: "https://19f41292356bb57816c73737d52d953022755133.googledrive.com/host/0ByFUqOHC2b93fjd1UFU5RG9FU2F6Qjh2RnRFbF9MZHZOQW1UbXY5WW1vQnJtR1F1SFdCUjQ/f6.html"`

It seems this is some python DDoS script by some "cloverdoser" script kid.

http://dianas2ana.blogspot.com/2015/07/ay-la-mau-cua-4-loai-f5-ddos-co-ban-cua.html

Thank you

**Comment by Stevie-Ray** [comment]
Hi @Mecanik, first sorry for the late reply. 

http://whois.domaintools.com/googledrive.com

It seems Google owns googledrive.com so I'm not sure if it a good idea to block the website as a whole.

That's what this script is doing!
