### ISSUE TITLE
Wrong nginx rules

### ISSUE THREAD

**Issue by yakky** [Stevie-Ray/htaccess-referral-spam-blacklist-block#17]
This rule https://github.com/Stevie-Ray/htaccess-referral-spam-blacklist-block/blob/master/referer-spam.conf#L4 actually prevents access from **any site except them spammers" one

**Comment by Stevie-Ray** [comment]
Personally I don't use NGINX, but I have checked the file using: http://wiki.nginx.org/Referrer_Spam_Blocking and everything seems alright.

**Comment by yakky** [comment]
I stumbled on that page too, but according to documentation (http://wiki.nginx.org/NginxHttpRefererModule#valid_referers) the attributes for `valid_reservers` are the referers which should be considered valid.

I was able to use this rule to restrict referers::

```
    if ($http_referer ~ "(100dollars-seo\.com|4webmasters\.org|...)") {
        set $prohibited "1";
    }
    if ($prohibited) {
        return 403;
    }
```
