### ISSUE TITLE
OR condition

### ISSUE THREAD

**Issue by jocelynduc** [Stevie-Ray/htaccess-referral-spam-blacklist-block#23]
I am not a mod_rewrite specialist, but is it normal that the zverokruh line does not contain an OR condition?

RewriteCond %{HTTP_REFERER} ^http(s)?://(www.)?._zazagames.org._$ [NC,OR]
RewriteCond %{HTTP_REFERER} ^http(s)?://(www.)?._zverokruh-shop.cz._$ [NC]
RewriteCond %{HTTP_REFERER} ^http(s)?://(www1?.)?._social-buttons.com._$ [NC,OR]

**Comment by Stevie-Ray** [comment]
```
RewriteCond %{HTTP_REFERER} ^http(s)?://(www.)?.zverokruh-shop.cz.$ [NC]
```

looks good, nc only is correct for the last line.

```
RewriteCond %{HTTP_REFERER} ^http(s)?://(www1?.)?.social-buttons.com.$ [NC,OR] 
```

but this rewrite rule is duplicate, i will remove it. thanks :+1:
