### ISSUE TITLE
fatal error in apache htaccess

### ISSUE THREAD

**Issue by odrescher** [Stevie-Ray/htaccess-referral-spam-blacklist-block#26]
It seems like the regular expression of video-production.com ist wrong. I have resolved this issue on my server by removing this line, but perhaps you like to fix it in your own code. 

This is from my apache-log:

[Mon Aug 17 11:26:05 2015] [alert] [client xx.xx.xx.xx] /var/www/vhosts/....../httpdocs/.htaccess: RewriteCond: cannot compile regular expression '^http(s)?://(www\.)?._video-\-\production\.com._$'

I think it should be like this (look at backslashes):
^http(s)?://(www.)?._video\-\-production.com._$

**Comment by Stevie-Ray** [comment]
there was a small typo, fixed it, thanks!!
