### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by thiagotalma** [Stevie-Ray/htaccess-referral-spam-blacklist-block#3]
Great job!

Is experiencing an error with the domain that uses special characters.

```
Syntax error on line 111 of /etc/apache2/httpd.conf:
RewriteCond: cannot compile regular expression '^http(s)?://(www\\.)?r????.??\\.*$'
Action 'configtest' failed.
The Apache error log may have more information.
```

I suggest removing this domain
https://github.com/Stevie-Ray/htaccess-referral-spam-blacklist-block/blob/master/.htaccess#L87

You can validate the file here: http://www.lyxx.com/freestuff/002.html

**Comment by Stevie-Ray** [comment]
it works on my apache server, but I will remove the domain..
