### ISSUE TITLE
Add Date / Version Information

### ISSUE THREAD

**Issue by TheBox193** [Stevie-Ray/htaccess-referral-spam-blacklist-block#36]
It might be nice to include the latest date or a version number as a comment at the top of the lists. It will make keeping track of updates/changes quite a bit easier when updating the list on multiple hosts.

I.E. `# Updated 2015-10-05`

Thoughts?

**Comment by Stevie-Ray** [comment]
see commit: 2f1815555857b48d0602a61c17a281ef32cdbaef
