### ISSUE TITLE
New referral spam

### ISSUE THREAD

**Issue by borisdifiore** [Stevie-Ray/htaccess-referral-spam-blacklist-block#38]
rankings-analytics.com
siteevaluation.com s
 mir-betting 
 salutmonreal.com 
 xn----7sbho2agebbhlivy.xn--p1ai 
burger-impria.com
clicksor

**Comment by Stevie-Ray** [comment]
siteevaluation.com and salutmontreal.com are already in our spamlist. 
So is clicksor (.com) and mir-betting (.ru)
it's: burger-imperia.com not burger-impria.com

please check the spam list before reporting an issue or new spammers.
