### ISSUE TITLE
Apache 2.4 compatibility

### ISSUE THREAD

**Issue by jiraky** [Stevie-Ray/htaccess-referral-spam-blacklist-block#4]
Dear developers, 
my question is about the upgrade from Apache 2.2 to Apache 2.4.
The code:

```
<IfModule mod_setenvif.c>
    SetEnvIfNoCase Referer yougetsignal.com spambot=yes
    ....

    Order allow,deny
    Allow from all
    Deny from env=spambo
</IfModule>
```

cause an error in `apache2ctl configtest`:

> AH00526: Syntax error on line XXX of /etc/apache2/sites-enabled/XXXX.conf:
> Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration
> Action 'configtest' failed.
> The Apache error log may have more information.

According to the official page, the directives must be updated.
[http://httpd.apache.org/docs/2.4/upgrading.html](http://httpd.apache.org/docs/2.4/upgrading.html)

How can I adapt the directive to Apache 2.4 sintax?

**Comment by Stevie-Ray** [comment]
In 2.4, such access control is done in the same way as other authorization checks, using the new module mod_authz_host. The old access control idioms should be replaced by the new authentication mechanisms, although for compatibility with old configurations, the new module mod_access_compat is provided. It means you have to add additional module to your httpd.conf (or equivalent file). Module can be loaded by adding such line (sometimes you just have to uncomment this line in configuration file): 

LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so

Or, try something like:

<IfModule mod_authz_host.c>
Require env=spambot denied
</IfModule>
