### ISSUE TITLE
about the generator

### ISSUE THREAD

**Issue by jusurb** [Stevie-Ray/htaccess-referral-spam-blacklist-block#53]
currently generator works only on windows, i can't make it work on other OSes.

But i could write a php script that would work on all OSes, windows, mac, linux, but you would have to have a php installed to run it.
Or we could set up a travis CI to run the php script on incoming change that would generate those files zip them and put them into release.

**Comment by julianxhokaxhiu** [comment]
I vote for Travis CI, one script to rule them all :)

**Comment by Stevie-Ray** [comment]
my vote also goes to Travis, would love to learn more about it!

**Comment by kkamkou** [comment]
+1 for travis + script or [wercker](http://wercker.com) + script.

**Comment by Stevie-Ray** [comment]
Can you guys help me out with this? Check the [develop](https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist/tree/develop) branch for current progress.

**Comment by jusurb** [comment]
you don't neet phpunit, there are no unit tests in your project, in your .travis.yml "script" line remove phpunit, and leave only one php version, as i don't think we have a need to run this script on different php versions to check compatibility:

``` yaml
php:
  - '5.6'
script: generator.php
```

unless you want to make sure that generate.php runs on all php versions :)

**Comment by Stevie-Ray** [comment]
@Gamesh thanks for the small fix'ups I changed the the travis CI file but it's [still failing](https://travis-ci.org/Stevie-Ray/apache-nginx-referral-spam-blacklist/builds/96732626) :(

`/home/travis/build.sh: line 45: generator.php: command not found`

**Comment by jusurb** [comment]
try adding php:

``` yaml
script: php generator.php
```

if it does not work it might be because travis is not building in the root dir of the probject.

**Comment by Stevie-Ray** [comment]
in combination with chmodding the .htaccess to 777 made the generator work, next step is to add a nginx version: Build [#25](https://travis-ci.org/Stevie-Ray/apache-nginx-referral-spam-blacklist/jobs/96873178) was fixed. thanks so much @Gamesh!!

**Comment by Stevie-Ray** [comment]
added the creation of a nignx referral-spam.conf file to the generator! Could somebody please look at the generator file?  And please tell me what's next :+1:

**Comment by jusurb** [comment]
@Stevie-Ray looks good. There is a bit of code duplication, but we can fix it later. Take a look here:
https://docs.travis-ci.com/user/deployment/releases/

**Comment by Stevie-Ray** [comment]
@Gamesh This works only if a tag is applied to a commit, see: [#37](https://travis-ci.org/Stevie-Ray/apache-nginx-referral-spam-blacklist/jobs/96934078) I'm not really sure if it works.. [This](http://stackoverflow.com/questions/28217556/travis-ci-auto-tag-build-for-github-release) method can maybe provide a solution for tags.

**Comment by jusurb** [comment]
@Stevie-Ray yes this method probably will work and will build on every commit. Usually people commit and repo owner does the merges/pull requests and then when he decides that this is release ready tags current version and the release is built. In your case i agree maybe a per commit build would be better.
the only way to see is to try it out :)

**Comment by Stevie-Ray** [comment]
Hi @Gamesh, deployment with tags is working, the only problem is that it doesn't do anything yet, see: [#51](https://travis-ci.org/Stevie-Ray/apache-nginx-referral-spam-blacklist) and the [travis file](https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist/blob/develop/.travis.yml) for reference, can you see what the problem is?

**Comment by jusurb** [comment]
hmm, but it published the files to the releases, what do you expect it to do ?
https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist/releases
by the way the global secure token should not be visible, put it in the environment variables.
and add `ls -aR` so the .htaccess would be visible.
also maybe we should zip both .conf and .htaccess and deploy the zip?

**Comment by julianxhokaxhiu** [comment]
@Gamesh in my opinion would be awesome if it could continuously update the two files in the repo, so in my case I can just use git pull and restart my nginx server to make it effective.

As it is now I have to download always the latest conf file and place if manually somewhere. Would it be possible to make travis commit the output on the master repo?

**Comment by Stevie-Ray** [comment]
isn't the secure token encrypted? I prefer updating the files in the repo (to the master branch), not as a release just like @julianxhokaxhiu mentioned :) anyway thanks for your help guys!

**Comment by julianxhokaxhiu** [comment]
@Stevie-Ray I prefer the master branch too. I'm not really a big fan of releases, at least, not for this project :)

**Comment by jusurb** [comment]
i thought that the whole point of having travis was to run maybe some checks, sort the domains.txt or do other stuff like validations of some kind and then release daily or on the need basis and maybe provide an auto update script for people that would always download the latest version from releases using github api.

**Comment by Stevie-Ray** [comment]
sorting the domains.txt would be nice. It would be awesome if you guys could help me with the travis file.

**Comment by julianxhokaxhiu** [comment]
I'm gonna have some Christmas holidays in the next days so I'll try to take a look at it :)

**Comment by Stevie-Ray** [comment]
I added a working sort function for the domains in [run.php](https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist/blob/develop/generator/run.php) file! I already wish you a merry Christmas ;-)
