### ISSUE TITLE
More Spam

### ISSUE THREAD

**Issue by anthonyscolaro** [Stevie-Ray/htaccess-referral-spam-blacklist-block#56]
I have a list of the top 50 spam that's being sent to one of our sites.  I already have your script running on our client servers yet these guys make it through.  I don't have a Windows machine to generate it myself.  Could you add these to your list?

https://docs.google.com/spreadsheets/d/11f2q6AqRuYgOqD0kLCipG9KYYL3vqqlNubrX0TLsuqs/edit#gid=1766249141

**Comment by Stevie-Ray** [comment]
Hi @anthonyscolaro thanks for sharing your spammers as you can see many of these sources are already listed in our domains.txt file. Currently i'm working on a .php version of the generator (I'm not using Windows either), please take  look at the develop branch!
