### ISSUE TITLE
New Spam

### ISSUE THREAD

**Issue by gagomap** [Stevie-Ray/htaccess-referral-spam-blacklist-block#60]
I have these domains in GA list:

share-buttons.xyz
traffic2cash.xyz
с.новым.годом.рф
website-stealer-warning.hdmoviecamera.net
website-stealer.nufaq.com
build-a-better-business.2your.site
topseoservices.co

Are they spam ? Ublock block me to visit all these sites.

**Comment by AdAvAn** [comment]
+1 
с.новым.годом.рф
santasgift.ml
website-stealer.nufaq.com
happy.new.yeartwit.com
rusexy.xyz

**Comment by Stevie-Ray** [comment]
Hi @gagomap  and @AdAvAn for с.новым.годом.рф see #59, share-buttons.xyz traffic2cash.xyz hdmoviecamera.net nufaq.com 2your.site topseoservices.co santasgift.ml yeartwit.com rusexy.xyz are all in the list please check the [domains list](https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist/blob/master/generator/domains.txt) before creating an issue

**Comment by gagomap** [comment]
Thank you :D

**Comment by ghost** [comment]
How can I get removed from this list?

**Comment by Stevie-Ray** [comment]
Go to your Google Analytics Admin panel and add a **custom** segment. This will 'filter' all old spam traffic.. 

![screen shot 2015-07-27 at 20 50 08](https://cloud.githubusercontent.com/assets/5747715/8914771/6a3a32a8-34a1-11e5-86ee-315a89fd5058.png)

like so:

| Filter | Session | **Include** |
| --- | --- | --- |
| Hostname | matches regex | `your-website\.com|www\.your-website\.com|other-possible-way\.com|googleusercontent\.com ]` |

| Filter | Session | **Exclude** |
| --- | --- | --- |
| Source | matches regex | `semalt\.com|anticrawler\.org|best-seo-offer|best-seo-solution|7makemoneyonline|-musicas*-gratis|kambasoft|savetubevideo|ranksonic|success-seo|medispainstitute|offers\.bycontext|100dollars-seo|buttons-for-website|buttons-for-your-website|sitevaluation|semaltmedia|videos-for-your-business|www\.Get-Free-Traffic-Now\.com|maxthon\.com` |

**Comment by uhlhosting** [comment]
How can one automate the htaccess replacement with the latest from github?
