### ISSUE TITLE
New kind of referral spam

### ISSUE THREAD

**Issue by janisf** [Stevie-Ray/htaccess-referral-spam-blacklist-block#71]
Hello everyone!
Today I noticed a new kind of referral spam in my Google Analytics account. It uses the parameter Landing Screen and provides a spammer's URL in it.
Has anyone else already encountered this?

P.S. I hope, I use the correct function to share my message. I am new to github, so please let me know, if creating an issue was wrong.

**Comment by Stevie-Ray** [comment]
Hi @janisf What do you mean with the parameter Landing Screen? In the "Landing Pages" report (Behavior --> Site Content --> Landing Pages) there is no spam on my account. Have you tried the [google-exclude.txt](https://raw.githubusercontent.com/Stevie-Ray/apache-nginx-referral-spam-blacklist/master/google-exclude.txt) for Google Analytics?

**Comment by janisf** [comment]
Hi @Stevie-Ray, yes, I am using google-exclude.txt and it blocks the spam completely. Just what I have seen recently appeared as a new kind of spam to me. I attached a screenshot to show what I mean.

<img width="952" alt="screen shot 2016-02-29 at 12 32 20" src="https://cloud.githubusercontent.com/assets/15192506/13393318/f3b8870c-dee0-11e5-9389-1676d87e220f.png">

**Comment by Stevie-Ray** [comment]
This kind of spam isn't new, multiple parameters in Google Analytics are being misused by the spammers. Thanks for reporting, luckily the exclude file works!
