### ISSUE TITLE
New ones spam

### ISSUE THREAD

**Issue by borisdifiore** [Stevie-Ray/htaccess-referral-spam-blacklist-block#90]
porodasobak.net
replicaclub.ru  
dimkino.ru
flooringinstallation-edmonton.com  
sad-torg.com.ua 
pornoklad.net  
e-collantes.com
keywords-monitoring-success.com
zvetki.ru
solitaire-game.ru
woman-orgasm.ru
euronis-free.com
sygraem.com
zaim-pod-zalog-krasnodar.ru
vesnatehno.com
iqoption-bin.com
pornoblood.com
ideibiznesa2015.ru
fix-website-errors.com
biznesluxe.ru

**Comment by snowman-repos** [comment]
cookie-law-enforcement-cc.xyz  
eu-cookie-law-enforcement-7.xyz

is there a way to just to all `*cookie-law-enforcement*` referrers?

**Comment by ghost** [comment]
cookie-law-enforcement-ee.xyz

forum.topic77220591.ghostvisitor.com
forum.topic77359479.ghostvisitor.com
