### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by pftiller** [Stevie-Ray/htaccess-referral-spam-blacklist-block#94]
I copied the regex spam rewrites from your .htaccess file to mine  hosted on my Apache server, replacing the far more limited list I had already in my .htaccess file. However, now I get an internal server error when I upload the updated .htaccess file to my server. When I remove the added spam rewrites, I can access again.

Server error says: "The server encountered an internal error or misconfiguration and was unable to complete your request" Any ideas?

**Comment by Stevie-Ray** [comment]
hi @pftiller, does this problem still occur? To me the .htaccess file works fine! thanks for letting me know.
