### ISSUE TITLE
Varnish version

### ISSUE THREAD

**Issue by jithujose** [Stevie-Ray/htaccess-referral-spam-blacklist-block#95]
Would be nice if you could generate also a varnish version of the blacklist.

Here is my gist:
https://gist.github.com/jithujose/402565c82cbc75e94f005f50fd03c674

**Comment by Stevie-Ray** [comment]
Hi @jithujose, I've added a Varnish file as you suggested. Could you check if it works as supposed? Thanks for your contribution!!

**Comment by jithujose** [comment]
It works.
