### ISSUE TITLE
Why Fiverr?

### ISSUE THREAD

**Issue by dvershinin** [Stevie-Ray/htaccess-referral-spam-blacklist-block#96]
I had a potential client from Fiverr visiting my website and getting blocked thanks to your config 👎 
## Expected Behavior

It should not be blocking referrs from fiverr.com
## Current Behavior

It blocks visitors from fiverr.com
## Possible Solution

Offending line: should be removed:

` "~*fiverr.com" 1; 
## Steps to Reproduce (for bugs)

Send link to your website where this configuration is enabled from within Fiverr.com private conversation.

**Comment by Stevie-Ray** [comment]
Hi @dvershinin sad to here a potential client got blocked from your website. I can't check all the domains, so thanks for your input. I removed fiverr from the list so it won't happen again!
